### ISSUE TITLE
Can not get stop notification when recording..

### ISSUE THREAD

**Issue by alexlee928** [dgutkai/AlexaDemo_OC#3]
Sorry for my poor english,I can not get stop notification when recording..              

```
 [[NSNotificationCenter defaultCenter] postNotificationName:NOTIFICATION_STOP object:self];
```

**Comment by dgutkai** [comment]
The recording can be stopped automatically according to the speech, you can also press the "speek" button to stop recording.
The volume of the recording is obtained in the code, and the recording is stopped automatically without speaking for a long time.
~~~  
    double lowPassResults = pow(10, (0.05 * [audioRecorder peakPowerForChannel:0]));
    NSLog(@"%lf",lowPassResults);
    if (lowPassResults < 0.009 && lowCount >= 1){
        lowCount++;
        if (lowCount > 20){
            lowCount = 0;
            // Stop Recoding
            [self talk2Action:nil];   
        }
    }else{
        lowCount = 1;
    }
~~~
---
The stop notification is sent only in the Bluetooth BLE instruction.

**Comment by alexlee928** [comment]
Thank you very much for your reply.Have a nice day.
