### ISSUE TITLE
[advice]What do you think of transfer voice by BLE?

### ISSUE THREAD

**Issue by alexlee928** [dgutkai/AlexaDemo_OC#4]
In your project, I saw the use of traditional Bluetooth recording to transfer voice data. If I want to use BLE for transmission, what do you think of this solution? Thank you.

**Comment by dgutkai** [comment]
You can compress and transmit audio data, and the data can be decoded after receiving the data through BLE. I tested this way, only after BLE5.0 protocol can support such a fast transmission rate, barely meet the requirements of speech recognition.
